FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/projeto_topicos_avancados_modulo_produto-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} projeto_topicos_avancados_modulo_produto-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/projeto_topicos_avancados_modulo_produto-0.0.1-SNAPSHOT.jar"]
